package com.metronom.ttt.app.machina;

public enum Events {
    EVENT_NEUTRAL,
    EVENT_BOARD_LOADED,
    EVENT_VALID_INPUT,
    EVENT_INVALID_INPUT,
    EVENT_WINNER_FOUND,
    EVENT_FULL_BOARD,
    EVENT_FIND_PLAYER,
    EVENT_EXIT_GAME,
    EVENT_RESET_GAME
}
